version: '3.9'
services:
# API services
  sk-api:
    image: quay.io/1qbit/qarrot-sk:api.v0.1
    build:
      context: ./
      dockerfile: docker/Dockerfile_api
    container_name: sk-api
    command: [ "/start-reload.sh" ]
    environment:
      MODULE_NAME: 'api.main'
      LOG_LEVEL_APP: 'DEBUG'
      LOG_FILE: "logs/worker.log"
    ports:
      - 8000:80
    volumes:
      - hansa_data:/hansa_data
      - ./api:/app/api
    networks:
      - hansa-network

  # sk-node:
  #   image: quay.io/1qbit/qarrot-sk:node.v0.1
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile_worker
  #   container_name: sk-node
  #   command: ["python3", "worker/sk_node.py"]
  #   volumes:
  #     - hansa_data:/hansa_data
  #     - ./worker:/app/worker
  #     - ./skalg:/app/skalg
  #     # volume mount dummy data
  #     - ./skalg/test.qasm:/hansa_data/test.qasm
  #   environment:
  #     LOG_LEVEL_APP: 'DEBUG'
  #     LOG_FILE: "logs/worker.log"
  #     JULIA_NUM_THREADS: 4
  #   networks:
  #     - hansa-network

  sk-node-julia:
    image: quay.io/1qbit/qarrot-sk:julia_node.v0.1
    build:
      context: ./
      dockerfile: docker/Dockerfile_worker_julia
    container_name: sk-node-julia
    command: ["julia", "worker/sk_node.jl"]
    volumes:
      - hansa_data:/hansa_data
      - ./worker:/app/worker
      - ./skalg:/app/skalg
      # volume mount dummy data
      - ./skalg/test.qasm:/hansa_data/test.qasm
    environment:
      JULIA_NUM_THREADS: 16
    networks:
      - hansa-network
      
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - hansa-network

  stats:
    image: virtualzone/docker-container-stats
    container_name: stats
    ports:
      - '8080:8080'
    environment:
      STATS_UPDATE_INTERVAL: 3
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

networks:
  hansa-network:
    name: hansa-network

volumes:
  hansa_data:
