# Base dependency image
FROM julia:1.8.5

ARG HOME_DIR=/app
ARG LOG_DIR=${HOME_DIR}/logs

WORKDIR ${HOME_DIR}

COPY . .


# Install Dependency Packages
WORKDIR ${HOME_DIR}/worker/sk_node
RUN julia requirements.jl

WORKDIR ${HOME_DIR}
RUN mkdir ${LOG_DIR}

