FROM python:3.10-slim
ARG HOME_DIR=/app
ARG LOG_DIR=/logs
ARG DATA_DIR=/hansa_data
ENV PYTHONPATH="${PYTHONPATH}:${HOME_DIR}"

RUN apt-get update && apt-get install -y build-essential \
  curl \
  vim

# Copy in the directories
COPY shared ${HOME_DIR}/shared
COPY compiler ${HOME_DIR}/compiler
COPY compiler/config.py ${HOME_DIR}/config.py
COPY compiler/data/compiler_input_test.txt ${DATA_DIR}/compiler_input_test.txt


# Install dependencies
WORKDIR ${HOME_DIR}
RUN pip install -r ${HOME_DIR}/shared/requirements.txt

# Create log directory
RUN mkdir ${LOG_DIR}

# Clean up tmp
RUN rm -rf /tmp
