FROM python:3.10-slim
ARG HOME_DIR=/app
ARG LOG_DIR=/logs
ARG DATA_DIR=/hansa_data
ENV PYTHONPATH="${PYTHONPATH}:${HOME_DIR}"

RUN apt-get update && apt-get install -y build-essential \
  curl \
  vim

# Copy in the directories
COPY shared ${HOME_DIR}/shared
COPY sk ${HOME_DIR}/sk
COPY sk/config.py ${HOME_DIR}/config.py
COPY sk/data/sk_input_test.qasm ${DATA_DIR}/sk_input_test.qasm


# Install dependencies
WORKDIR ${HOME_DIR}
RUN pip install -r ${HOME_DIR}/shared/requirements.txt

# Create log directory
RUN mkdir ${LOG_DIR}

# Clean up tmp
RUN rm -rf /tmp
