name: Build Test Images
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the images'
        required: true
        type: string
      build_sk:
        description: 'Build sk'
        required: false
        type: boolean
      build_transpiler:
        description: 'Build transpiler'
        required: false
        type: boolean
      build_compiler:
        description: 'Build compiler'
        required: false
        type: boolean
      build_ftqc:
        description: 'Build ftqc'
        required: false
        type: boolean
      build_pre:
        description: 'Build pre'
        required: false
        type: boolean
      build_qare:
        description: 'Build qare'
        required: false
        type: boolean

jobs:
  build_and_push_to_quay:
    name: Build the image and push it to Quay registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}    

      - name: Set flag whether to build tool or not
        id: build-tools-flag
        run: |
          echo "::set-output name=BUILD_SK::${{ github.event.inputs.build_sk }}"
          echo "::set-output name=BUILD_TRANSPILER::${{ github.event.inputs.build_transpiler }}"
          echo "::set-output name=BUILD_COMPILER::${{ github.event.inputs.build_compiler }}"
          echo "::set-output name=BUILD_FTQC::${{ github.event.inputs.build_ftqc }}"
          echo "::set-output name=BUILD_PRE::${{ github.event.inputs.build_pre }}"
          echo "::set-output name=BUILD_QARE::${{ github.event.inputs.build_qare }}"

      - name: Generate tag
        id: tag-generator
        run: |
          sha=${GITHUB_SHA::8}
          timestamp=$(date +'%Y.%m.%d')
          version=${{ github.event.inputs.version }}
          echo "::set-output name=BUILD_ID::${timestamp}.${sha}.${version}"

      - name: Build and push sk image to Quay
        uses: docker/build-push-action@v2
        if: steps.build-tools-flag.outputs.BUILD_SK == 'true'
        with:
          file: ./sk/Dockerfile_sk
          tags: quay.io/1qbit/qarrot-tests:sk.${{ steps.tag-generator.outputs.BUILD_ID }}
          push: true

      - name: Build and push transpiler image to Quay
        if: steps.build-tools-flag.outputs.BUILD_TRANSPILER == 'true'
        uses: docker/build-push-action@v2
        with:
          file: ./transpiler/Dockerfile_transpiler
          tags: quay.io/1qbit/qarrot-tests:transpiler.${{ steps.tag-generator.outputs.BUILD_ID }}
          push: true

      - name: Build and push compiler image to Quay
        uses: docker/build-push-action@v2
        with:
          file: ./compiler/Dockerfile_compiler
          tags: quay.io/1qbit/qarrot-tests:compiler.${{ steps.tag-generator.outputs.BUILD_ID }}
          push: true

      - name: Build and push ftqc image to Quay
        uses: docker/build-push-action@v2
        with:
          file: ./ftqc/Dockerfile_ftqc
          tags: quay.io/1qbit/qarrot-tests:ftqc.${{ steps.tag-generator.outputs.BUILD_ID }}
          push: true

      - name: Build and push pre image to Quay
        uses: docker/build-push-action@v2
        with:
          file: ./pre/Dockerfile_pre
          tags: quay.io/1qbit/qarrot-tests:pre.${{ steps.tag-generator.outputs.BUILD_ID }}
          push: true

      - name: Build and push qare image to Quay
        uses: docker/build-push-action@v2
        with:
          file: ./qare/Dockerfile_qare
          tags: quay.io/1qbit/qarrot-tests:qare.${{ steps.tag-generator.outputs.BUILD_ID }}
          push: true
          