name: Pull Request Workflow
on:
  - pull_request
jobs:
  run_tests:
    name: Run tests on pull requests
    runs-on: ubuntu-latest
    environment: local

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Build hansa compiler image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          tags: quay.io/1qbit/hansa:compiler.pr_review
          push: false

      - name: Run tests
        run: 
             docker run quay.io/1qbit/hansa:compiler.pr_review bash # -c "pytest" uncomment after test have been fixed